'use strict';
function bind(){
 document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>go(b.dataset.nav));
 document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>go(b.dataset.goto));
 const pd=document.getElementById('prevDay');if(pd)pd.onclick=()=>setDay(S.selectedDay-1);
 const nd=document.getElementById('nextDay');if(nd)nd.onclick=()=>setDay(S.selectedDay+1);
 const di=document.getElementById('dayInput');if(di)di.onchange=()=>setDay(Number(di.value));
 const it=document.getElementById('intensity');if(it)it.onchange=()=>{S.intensity=it.value;save();render()};
 document.querySelectorAll('[data-task]').forEach(b=>b.onclick=e=>{e.stopPropagation();const k=dayKey(S.selectedDay,b.dataset.task);S.taskDone[k]=!S.taskDone[k];if(!S.startedAt)S.startedAt=new Date().toISOString();save();render()});
 document.querySelectorAll('[data-gnode]').forEach(b=>b.onclick=()=>{UI.gNode=Number(b.dataset.gnode);UI.gQ=0;UI.gSel=null;UI.gAnswered=false;render()});
 document.querySelectorAll('[data-gopt]').forEach(b=>b.onclick=()=>{if(!UI.gAnswered){UI.gSel=Number(b.dataset.gopt);render()}});
 const rg=document.getElementById('recommendedG');if(rg)rg.onclick=()=>{UI.gNode=recommendedGrammarNode();UI.gQ=daily().grammar%grammarQuestions(GRAMMAR[UI.gNode]).length;UI.gSel=null;UI.gAnswered=false;render()};
 const sg=document.getElementById('submitG');if(sg)sg.onclick=submitGrammar;
 const ng=document.getElementById('nextGQ');if(ng)ng.onclick=()=>{UI.gNode=recommendedGrammarNode();UI.gQ=daily().grammar%grammarQuestions(GRAMMAR[UI.gNode]).length;UI.gSel=null;UI.gAnswered=false;render()};
 document.querySelectorAll('[data-inputtab]').forEach(b=>b.onclick=()=>{UI.inputTab=b.dataset.inputtab;render()});
 document.querySelectorAll('[data-ropt]').forEach(b=>b.onclick=()=>answerReading(b.dataset.ropt));
 const nr=document.getElementById('nextReading');if(nr)nr.onclick=completeReading;
 document.querySelectorAll('[data-lopt]').forEach(b=>b.onclick=()=>answerListening(b.dataset.lopt));
 const nl=document.getElementById('nextListening');if(nl)nl.onclick=completeListening;
 const pl=document.getElementById('playListen');if(pl)pl.onclick=playListening;
 const ss=document.getElementById('showScript');if(ss)ss.onclick=()=>{const box=document.getElementById('scriptBox');box.style.display=box.style.display==='none'?'block':'none'};
 document.querySelectorAll('[data-outputtab]').forEach(b=>b.onclick=()=>{UI.outputTab=b.dataset.outputtab;UI.writeMsg='';UI.appMsg='';UI.speakMsg='';render()});
 const sa=document.getElementById('submitApp');if(sa)sa.onclick=submitApp;
 const sw=document.getElementById('submitWriting');if(sw)sw.onclick=submitWriting;
 const rb=document.getElementById('recBtn');if(rb)rb.onclick=toggleRecording;
 const cs=document.getElementById('completeSpeak');if(cs)cs.onclick=completeSpeaking;
 const eb=document.getElementById('exportBtn');if(eb)eb.onclick=exportBackup;
 const im=document.getElementById('importFile');if(im)im.onchange=importBackup;
 const re=document.getElementById('resetBtn');if(re)re.onclick=resetAll;
 document.querySelectorAll('[data-fixerr]').forEach(b=>b.onclick=()=>{S.errors.splice(Number(b.dataset.fixerr),1);save();render()});
}
function setDay(n){n=Math.max(1,Math.min(50,n||1));S.selectedDay=n;UI.gNode=recommendedGrammarNode(n,0);UI.gQ=0;UI.gSel=null;UI.gAnswered=false;save();render()}
function submitGrammar(){if(UI.gSel===null)return;const g=GRAMMAR[UI.gNode],qs=grammarQuestions(g),q=qs[UI.gQ%qs.length];UI.gAnswered=true;S.grammar.attempts++;daily().grammar++;S.grammar.skill[g.id]=S.grammar.skill[g.id]||{a:0,c:0};S.grammar.skill[g.id].a++;if(UI.gSel===q[2]){S.grammar.correct++;S.grammar.skill[g.id].c++}else{S.errors.unshift({skill:g.name,original:q[1][UI.gSel],correct:q[1][q[2]],why:q[3],at:new Date().toISOString()})}if(!S.startedAt)S.startedAt=new Date().toISOString();save();render()}
function answerReading(k){const [qi,oi]=k.split(':').map(Number),r=currentReading(),key=`${S.selectedDay}:${r.id}:${qi}`;if(S.reading.answers[key]!==undefined)return;const q=r.qs[qi];S.reading.answers[key]=oi;S.reading.attempts++;if(oi===q[2])S.reading.correct++;save();render()}
function completeReading(){const r=currentReading(),base=`${S.selectedDay}:${r.id}`;if(!r.qs.every((_,qi)=>S.reading.answers[`${base}:${qi}`]!==undefined))return;daily().reading++;S.reading.index++;save();render()}
function answerListening(k){const [qi,oi]=k.split(':').map(Number),l=currentListening(),key=`${S.selectedDay}:${l.id}:${qi}`;if(S.listening.answers[key]!==undefined)return;const q=l.qs[qi];S.listening.answers[key]=oi;S.listening.attempts++;if(oi===q[2])S.listening.correct++;save();render()}
function completeListening(){const l=currentListening(),base=`${S.selectedDay}:${l.id}`;if(!l.qs.every((_,qi)=>S.listening.answers[`${base}:${qi}`]!==undefined))return;daily().listening++;S.listening.index++;save();render()}
function playListening(){const l=currentListening();if(!('speechSynthesis'in window)){alert('当前浏览器不支持语音合成。请使用最新版 Chrome / Edge / Safari。');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(l.script);u.lang='fr-FR';u.rate=S.selectedDay<10?.82:S.selectedDay<25?.9:.98;speechSynthesis.speak(u)}
function submitApp(){const a=currentApplication(),el=document.getElementById('appText'),t=(el.value||'').trim();if(t.length<20){UI.appMsg='内容太短：先写至少 3 句，再保存。';render();return}const low=t.toLowerCase(),hits=a.keys.filter(k=>low.includes(k));S.application.records.push({day:S.selectedDay,title:a.title,text:t,hits,at:new Date().toISOString()});S.application.count++;S.application.index++;daily().application++;UI.appMsg=`已保存。命中 ${hits.length}/${a.keys.length} 个任务关键词。这个检查只判断任务结构，不代表法语水平。`;save();render()}
function wordCount(t){return t.trim().split(/\s+/).filter(Boolean).length}
function submitWriting(){const w=currentWriting(),t=(document.getElementById('writeText').value||'').trim(),n=wordCount(t);if(!t){UI.writeMsg={ok:false,text:'还没有写作内容。'};render();return}const connectors=['d’abord','ensuite','cependant','pourtant','par exemple','donc','à mon avis','en conclusion','pour conclure'],low=t.toLowerCase(),hits=connectors.filter(x=>low.includes(x)),paras=t.split(/\n\s*\n/).filter(x=>x.trim()).length;S.writing.records.push({day:S.selectedDay,title:w.title,text:t,words:n,connectors:hits,paragraphs:paras,at:new Date().toISOString()});S.writing.count++;S.writing.index++;daily().writing++;UI.writeMsg={ok:n>=w.min,text:`已保存：约 ${n} 词，检测到 ${hits.length} 个常见连接表达，${Math.max(1,paras)} 个段落。${n>=w.min?'达到本次最低字数要求；这些只是结构证据，不代表写作分数。':`当前目标至少 ${w.min} 词，请继续扩展。`}`};save();render()}
async function toggleRecording(){if(UI.recording){stopRecording();return}if(!navigator.mediaDevices||!window.MediaRecorder){alert('当前浏览器不支持网页录音。请使用最新版 Chrome / Edge / Safari，并允许麦克风权限。');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});UI.media=new MediaRecorder(stream);UI.chunks=[];UI.media.ondataavailable=e=>{if(e.data.size)UI.chunks.push(e.data)};UI.media.onstop=async()=>{const sec=Math.max(1,Math.round((Date.now()-UI.recStart)/1000));const blob=new Blob(UI.chunks,{type:UI.media.mimeType||'audio/webm'});const p=currentSpeaking(),id=`d${S.selectedDay}-s${Date.now()}`;const ok=await storeAudio(id,blob);S.speaking.records.push({id,day:S.selectedDay,title:p.title,sec,stored:ok,at:new Date().toISOString()});S.speaking.totalSec+=sec;S.speaking.count++;S.speaking.index++;daily().speaking++;save();UI.speakMsg=`录音 ${fmtSec(sec)} 已记录${ok?'并保存到账号':'，但录音保存失败'}。请回听后按任务清单自检。`;stream.getTracks().forEach(t=>t.stop());render()};UI.media.start();UI.recording=true;UI.recStart=Date.now();UI.recTimer=setInterval(()=>{const el=document.getElementById('recTimer');if(el)el.textContent=fmtSec(Math.round((Date.now()-UI.recStart)/1000))},500);render()}catch(e){alert('无法开始录音：'+e.message)}}
function stopRecording(){if(UI.media&&UI.media.state!=='inactive')UI.media.stop();UI.recording=false;if(UI.recTimer)clearInterval(UI.recTimer);UI.recTimer=null}
function completeSpeaking(){const p=currentSpeaking();S.speaking.records.push({id:null,day:S.selectedDay,title:p.title,sec:0,stored:false,manual:true,at:new Date().toISOString()});S.speaking.count++;S.speaking.index++;daily().speaking++;UI.speakMsg='已记录一次线下口语练习。由于没有可靠自动语音评分，本次不会改变任何“口语能力分数”。';save();render()}

const V13_VERSION='1.3';
S.daily=S.daily||{};S.version=V13_VERSION;save();
top=function(title,sub){return `<div class="top"><div><div class="eyebrow">DELF50 · WEB V${V13_VERSION}</div><h1>${title}</h1><div class="muted">${sub}</div></div></div>`};
progressPage=function(){const completed=totalCompletedTasks();return `${top('进度与存储','只有有测量依据的数据才显示能力指标；其他项目显示训练量。')}<div class="card"><h2>客观测量</h2><div class="grid3">${measured('语法客观正确率',S.grammar)}${measured('阅读客观正确率',S.reading)}${measured('听力客观正确率',S.listening)}</div><div class="callout warn" style="margin-top:10px">正确率只有在样本量足够时才有参考意义。建议每项至少完成 20–30 道题后再观察趋势。</div></div><div class="card"><h2>训练量（不是能力分数）</h2><div class="grid3"><div class="metric"><span>实际训练记录</span><b>${completed}</b><span>题目/任务/完成块</span></div><div class="metric"><span>应用任务</span><b>${S.application.count}</b><span>真实情境训练</span></div><div class="metric"><span>写作任务</span><b>${S.writing.count}</b><span>保存字数与结构</span></div><div class="metric"><span>口语任务</span><b>${S.speaking.count}</b><span>不生成水平百分比</span></div><div class="metric"><span>口语录音</span><b>${fmtSec(S.speaking.totalSec)}</b><span>累计录音时长</span></div><div class="metric"><span>错题</span><b>${S.errors.length}</b><span>待回炉</span></div></div></div><div class="card"><h2>连续学习存储</h2><div class="callout good">学习状态每次操作后自动写入浏览器 localStorage；口语录音使用 IndexedDB。建议每周导出 JSON 备份，防止清理浏览器数据导致丢失。</div><div class="row wrap" style="margin-top:10px"><button class="btn" id="exportBtn">导出学习备份</button><label class="btn secondary" style="cursor:pointer">导入备份<input id="importFile" type="file" accept="application/json" style="display:none"></label><button class="btn secondary" id="resetBtn">重置为全0</button></div><div class="storage">最后保存：${S.lastSavedAt?new Date(S.lastSavedAt).toLocaleString():'尚未开始学习'} · 数据版本 ${V13_VERSION}</div></div>`};
exportBackup=function(){const data={app:'DELF50',version:V13_VERSION,exportedAt:new Date().toISOString(),state:S,note:'口语音频保存在浏览器 IndexedDB 中，不包含在 JSON 备份内。'};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`delf50-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
importBackup=function(e){const f=e.target.files&&e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{try{const x=JSON.parse(rd.result);if(!x.state)throw Error('备份格式不正确');S=Object.assign(fresh(),x.state);S.daily=S.daily||{};S.version=V13_VERSION;save();alert('学习备份已导入。');render()}catch(err){alert('导入失败：'+err.message)}};rd.readAsText(f)};
resetAll=function(){if(confirm('这会把学习状态重置为全0。口语录音不会自动删除。确定吗？')){S=fresh();S.daily={};S.version=V13_VERSION;UI.gNode=0;save();render()}};
UI.gNode=recommendedGrammarNode(S.selectedDay,0);
render();
