'use strict';
function fresh(){return{version:VERSION,selectedDay:1,intensity:'standard',taskDone:{},grammar:{attempts:0,correct:0,skill:{}},reading:{attempts:0,correct:0,index:0,answers:{}},listening:{attempts:0,correct:0,index:0,answers:{}},application:{count:0,index:0,records:[]},writing:{count:0,index:0,records:[]},speaking:{count:0,totalSec:0,index:0,records:[]},errors:[],startedAt:null,lastSavedAt:null}};
function load(){try{const raw=localStorage.getItem(KEY);return raw?Object.assign(fresh(),JSON.parse(raw)):fresh()}catch(e){return fresh()}}
let S=load(),view='today',UI={gNode:0,gQ:0,gSel:null,gAnswered:false,appMsg:'',writeMsg:'',readMsg:'',listenMsg:'',speakMsg:'',recording:false,recStart:0,recTimer:null,media:null,chunks:[]};
const loaded={body:bodyOf(S),at:S.lastSavedAt};let savedBody=loaded.body;
/* The state's content, independent of key order and of lastSavedAt itself. */
function bodyOf(s){const{lastSavedAt,...rest}=s;return JSON.stringify(rest,(k,v)=>{if(v&&typeof v==='object'&&!Array.isArray(v)){const o={};for(const x of Object.keys(v).sort())o[x]=v[x];return o}return v})}
/* lastSavedAt is the time of the last change, so a save that changes nothing leaves the state, and the server, untouched. */
function save(){const body=bodyOf(S);if(body===loaded.body)S.lastSavedAt=loaded.at;else if(body!==savedBody)S.lastSavedAt=new Date().toISOString();savedBody=body;try{localStorage.setItem(KEY,JSON.stringify(S))}catch(e){} }
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function pct(c,t){return t?Math.round(c/t*100):null}
function fmtMin(m){const h=Math.floor(m/60),r=m%60;return h?(r?`${h}小时${r}分`:`${h}小时`):`${r}分`}
function fmtSec(s){const m=Math.floor(s/60),r=s%60;return `${m}:${String(r).padStart(2,'0')}`}
function phase(day=S.selectedDay){return day<=18?'阶段1 · 语法手感':day<=30?'阶段2 · 应用迁移':day<=40?'阶段3 · DELF专项':'阶段4 · 模考提分'}
function phaseNote(day=S.selectedDay){return day<=18?'新知识控制在有限范围，重点做“理解→识别→变形→纠错→造句→应用”。':day<=30?'不再大量扩语法，而是把已有结构用于叙事、请求、建议、投诉和观点。':day<=40?'按 DELF 四项任务训练时间、信息定位、160词写作结构和三类口语任务。':'模拟考与错因修复交替，不追求继续学新知识。'}
function buildTasks(day){const d=DAYS[day-1],mins=LEVELS[S.intensity].mins;const late=day>=40;const names=late?['模拟/语法修复','情境应用/口试','词块回顾','听力计时','阅读计时','写作计时','口语录音','错题复盘']:['语法专项','应用专项','主题词块','听力训练','阅读训练','写作训练','口语训练','错题与复习'];const desc=[
 `${d[1]}：先规则/例句，再做识别、变形、纠错和自由造句。`,
 `${d[2]} · ${d[3]}：用今天语法完成真实任务，不只做填空。`,
 `${d[3]}：主动掌握高频词组与搭配；优先句块而非孤立单词。`,
 `${d[3]}：第一遍抓主旨，第二遍抓细节/数字，第三遍对照关键词复盘。`,
 `${d[3]}：先限时定位信息，再总结段落主旨和作者态度。`,
 day>=35?'按 DELF B1 写作方式：读题→10分钟列点→约30分钟写作→5分钟检查；正式目标≥160词。':'从 60–120 词逐步增加，必须调用当天语法/连接词；Day 35 后进入≥160词。',
 day>=37?'按 DELF 口语类型练习：自我介绍、互动、观点表达；网页录音并回听。':'录音 1–3 分钟，把当天结构说出来；只记录训练量，不伪造能力分数。',
 '复习今天错题 + 48小时内旧错题；重写/重说错误句，并整理3–5条可复用表达。'
 ];return names.map((n,i)=>({id:['grammar','app','vocab','listen','read','write','speak','review'][i],name:n,min:mins[i],desc:desc[i]}))}
function plannedMinutes(day=S.selectedDay){return buildTasks(day).reduce((a,b)=>a+b.min,0)}
function dayKey(day,id){return `${day}:${id}`}
function dayDoneMinutes(day=S.selectedDay){return buildTasks(day).reduce((a,t)=>a+(S.taskDone[dayKey(day,t.id)]?t.min:0),0)}
function totalCompletedTasks(){return Object.values(S.taskDone).filter(Boolean).length}
function measured(label,stat){const p=pct(stat.correct,stat.attempts);return `<div class="metric"><span>${label}</span><b>${p===null?'未评估':p+'%'}</b><span>${p===null?'完成客观题后显示':`${stat.correct}/${stat.attempts} 正确`}</span></div>`}
function nav(){const items=[['today','⌂','今日'],['grammar','G','语法'],['input','耳','听读'],['output','说','写说'],['delf','D','DELF'],['progress','◎','进度']];return `<div class="nav">${items.map(x=>`<button class="${view===x[0]?'on':''}" data-nav="${x[0]}"><b>${x[1]}</b>${x[2]}</button>`).join('')}</div>`}
function top(title,sub){return `<div class="top"><div><div class="eyebrow">DELF50 · WEB V${VERSION}</div><h1>${title}</h1><div class="muted">${sub}</div></div></div>`}
function dayControls(){return `<div class="card"><div class="row wrap"><div><b>学习进度由你掌控</b><div class="muted">推荐按顺序学习，但可随时提前或回看任意一天。跳跃不会自动增加能力分数。</div></div><div class="dayctl"><button class="btn secondary small" id="prevDay">←</button><label class="muted">Day <input id="dayInput" type="number" min="1" max="50" value="${S.selectedDay}"></label><button class="btn secondary small" id="nextDay">→</button><select id="intensity">${Object.entries(LEVELS).map(([k,v])=>`<option value="${k}" ${S.intensity===k?'selected':''}>${v.label}</option>`).join('')}</select></div></div></div>`}
function today(){const d=DAYS[S.selectedDay-1],tasks=buildTasks(S.selectedDay),done=dayDoneMinutes(),total=plannedMinutes();return `${top(`Day ${S.selectedDay} · ${d[0]}`,`${phase()} · ${d[4]}`)}${dayControls()}<div class="card hero"><div class="row wrap"><div><div class="eyebrow" style="color:#d4eee7">TODAY PLAN</div><h2>${phase()}</h2><div class="muted" style="color:#d8eee8">${phaseNote()}</div></div><div><b>${fmtMin(total)}</b><div class="muted" style="color:#d8eee8">计划学习量</div></div></div><div class="grid3" style="margin-top:12px"><div class="metric"><span>今日完成</span><b>${Math.round(done/total*100)||0}%</b><span>${fmtMin(done)} / ${fmtMin(total)}</span></div><div class="metric"><span>累计任务</span><b>${totalCompletedTasks()}</b><span>只代表训练完成量</span></div><div class="metric"><span>当前主题</span><b style="font-size:14px">${d[3]}</b><span>${d[2]}</span></div></div></div><div class="card"><div class="row"><b>今日学习块</b><span class="pill blue">总量 ${fmtMin(total)}</span></div>${tasks.map(t=>`<div class="task"><div class="time">${t.min}<br>min</div><div><b>${t.name}</b><div class="desc">${t.desc}</div></div><button class="check ${S.taskDone[dayKey(S.selectedDay,t.id)]?'done':''}" data-task="${t.id}" title="标记训练块完成">${S.taskDone[dayKey(S.selectedDay,t.id)]?'✓':'○'}</button></div>`).join('')}</div><div class="card"><b>今天的新旧比例</b><div class="callout blue">${S.selectedDay<=18?'约 25–35% 新知识 + 65–75% 操练、复习与应用。每天最多推进 1–2 个核心语法概念。':S.selectedDay<=30?'新语法显著降低，以旧语法在新情境中的调用为主。':S.selectedDay<=40?'基本停止系统扩展语法，重点训练 DELF 任务和限时表现。':'原则上不学新语法：模拟 → 找错因 → 定向修复 → 再模拟。'}</div></div>`}
function grammar(){const g=GRAMMAR[UI.gNode],q=g.qs[UI.gQ];const st=S.grammar.skill[g.id]||{a:0,c:0};return `${top('Grammar Gym','18 个高收益节点；每个节点都有 DELF 用途、例句与客观题。')}<div class="grid2"><div><div class="card"><span class="pill">${g.level}</span><span class="pill blue">${g.use}</span><h2>${UI.gNode+1}. ${g.name}</h2><div class="callout blue">例句：${g.ex.map(esc).join(' · ')}</div><div class="divider"></div><div class="muted">节点客观正确率：${st.a?pct(st.c,st.a)+'%':'未评估'} · 已做 ${st.a} 题</div><h2>${esc(q[0])}</h2>${q[1].map((o,i)=>`<button class="opt ${UI.gSel===i?'on':''} ${UI.gAnswered?(i===q[2]?'good':UI.gSel===i?'bad':''):''}" data-gopt="${i}" ${UI.gAnswered?'disabled':''}>${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}${UI.gAnswered?`<div class="callout ${UI.gSel===q[2]?'good':'bad'}"><b>${UI.gSel===q[2]?'正确':'需要修复'}</b><br>${q[3]}</div><button class="btn" id="nextGQ">下一题</button>`:`<button class="btn" id="submitG" ${UI.gSel===null?'disabled':''}>提交答案</button>`}</div></div><div><div class="card"><b>语法知识地图</b>${GRAMMAR.map((x,i)=>{const z=S.grammar.skill[x.id]||{a:0,c:0};return `<div class="node ${i===UI.gNode?'current':''}" data-gnode="${i}"><b>${i+1}. ${x.name}</b> <span class="pill">${x.level}</span><div class="muted">${x.use} · ${z.a?pct(z.c,z.a)+'%':'未评估'}</div></div>`}).join('')}</div></div></div>`}
function inputPage(){const r=READINGS[S.reading.index%READINGS.length],l=LISTENINGS[S.listening.index%LISTENINGS.length];return `${top('听力与阅读','这两项只用客观题正确率评估；没做题时显示“未评估”。')}<div class="tabs"><button class="${UI.inputTab!=='listening'?'on':''}" data-inputtab="reading">阅读</button><button class="${UI.inputTab==='listening'?'on':''}" data-inputtab="listening">听力</button></div>${UI.inputTab==='listening'?listeningView(l):readingView(r)}`}
function readingView(r){return `<div class="card"><div class="row"><div><span class="pill">Compréhension écrite</span><h2>${r.title}</h2></div><div class="score">${S.reading.attempts?pct(S.reading.correct,S.reading.attempts)+'%':'未评估'}</div></div><p style="line-height:1.75">${r.text}</p>${r.qs.map((q,qi)=>`<div class="divider"></div><b>${qi+1}. ${q[0]}</b>${q[1].map((o,oi)=>{const a=S.reading.answers[`${S.reading.index}:${qi}`];const cls=a===oi?(oi===q[2]?'good':'bad'):'';return `<button class="opt ${cls}" data-ropt="${qi}:${oi}">${esc(o)}</button>`}).join('')}`).join('')}<button class="btn" id="nextReading">下一篇阅读</button></div>`}
function listeningView(l){return `<div class="card"><div class="row wrap"><div><span class="pill">Compréhension de l’oral</span><h2>${l.title}</h2></div><div class="score">${S.listening.attempts?pct(S.listening.correct,S.listening.attempts)+'%':'未评估'}</div></div><div class="callout blue">先不看文本。点击播放，建议听两遍再答题。语音由浏览器法语 TTS 生成，因此它是训练素材，不等同于官方录音。</div><div class="row wrap" style="margin-top:10px"><button class="btn" id="playListen">▶ 播放法语音频</button><button class="btn secondary" id="showScript">查看/隐藏文本</button></div><div id="scriptBox" class="callout warn" style="display:none;margin-top:10px">${esc(l.script)}</div>${l.qs.map((q,qi)=>`<div class="divider"></div><b>${qi+1}. ${q[0]}</b>${q[1].map((o,oi)=>{const a=S.listening.answers[`${S.listening.index}:${qi}`];const cls=a===oi?(oi===q[2]?'good':'bad'):'';return `<button class="opt ${cls}" data-lopt="${qi}:${oi}">${esc(o)}</button>`}).join('')}`).join('')}<button class="btn" id="nextListening">下一段听力</button></div>`}
